spring:
  profiles:
    active: dev

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_db
    username: test_user
    password: test_user
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/mongodb-sample # connection URL
      database: mongodb-sample
      #      authentication-database: mongovwdb
      #      grid-fs-database:
      username: test_user
      password: test_user

server:
  port: 9001

---

spring:
  profiles: docker
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/sample_db
    username: test_user
    password: test_user
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: mongodb-server

server:
  port: 9000
